export const LOADING_RICH = "LOADING_RICH";
export const LOAD_PREVIEW = "GET_PREVIEW";
export const LOAD_RICH = "LOAD_RICH";
export const LOAD_SINGLE_PRODUCT = "LOAD_SINGLE_PRODUCT";
export const CLEAR_SINGLE_PRODUCT = "CLEAR_SINGLE_PRODUCT";
